[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "queensgame"
requires-python = ">=3.9"
version = "0.1"
description = "A package to solve the Queens Game"